### ISSUE TITLE
Depends on ORO, a project that Apache retired in 2010

### ISSUE THREAD

**Issue by RadicalQuiver** [arimus/jmimemagic#26]
Would you consider switching to the RegEx handler in the JDK ? this looks cool, but I don't want to bake in a dependency on something dead.

**Comment by arimus** [comment]
Certainly.  At the time, ORO was a better option.  If you create a pull request and the tests pass, I'll merge it.

**Comment by madness-inc** [comment]
Hi,

this can be closed as it is fixed in #33 with version 0.1.5

Regards
Matthias
