### ISSUE TITLE
Licensing information is inconsistant

### ISSUE THREAD

**Issue by hrieke** [arimus/jmimemagic#36]
Hey,

Nifty code and very useful.  However, while you state Apache License 2.0 in your readme / license.txt file, the source code headers still include LPLG.

**Comment by arimus** [comment]
Thanks. Yeah, may be some legacy items in there that we need to remove. I'll take a look. Be assured, you can use it under the terms of the Apache License though. More folks wanted a more liberal license, so it was switched over some years ago.

**Comment by hrieke** [comment]
Just in my job we check the source code first for the license, then the project.
If there is a difference, the license closest to the source code wins.  In your case it would be LPGL.
I'll certainly point out this thread (and see if I can get an override).
Thanks

**Comment by arimus** [comment]
I've just pushed a commit to remove the old reference: d6dd3092cc2ab4c545f54a53a14559efd546d9d8
